version: '3.9'

services:

  copycord:
    container_name: copycord
    image: copycord
    restart: on-failure:5
    build: .
    ports:
      - '3001-3005:3001-3005'
    volumes:
      - ./:/srv/copycord/
    environment:
      THREADS: ${THREADS:-1}
      HTTP_PORT: 3001
      WS_PORT: 3002
      CDN_PORT: 3003
      RTC_PORT: 3004
      ADMIN_PORT: 3005

networks:
  default:
    name: copycord
    driver: bridge
